# Generated by Django 5.1.4 on 2024-12-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_accounts', '0002_remove_teacherprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='class_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
