# Generated by Django 5.1.4 on 2024-12-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_accounts', '0003_teacherprofile_class_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subject',
        ),
    ]
