# Generated by Django 5.1.4 on 2024-12-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_accounts', '0004_remove_teacherprofile_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='class_code',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='course_name',
        ),
    ]
