# Generated by Django 5.1.4 on 2024-12-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherArea', '0004_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
    ]
