# Generated by Django 5.1.4 on 2024-12-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherArea', '0006_studentsubmission'),
        ('security_accounts', '0005_remove_teacherprofile_class_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('class_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='TeacherArea.class')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='security_accounts.teacherprofile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='security_accounts.studentprofile')),
            ],
        ),
    ]
