# Generated by Django 5.1.4 on 2024-12-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherArea', '0007_message'),
        ('security_accounts', '0005_remove_teacherprofile_class_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_at',
        ),
        migrations.AlterField(
            model_name='message',
            name='class_associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeacherArea.class'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_accounts.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_accounts.studentprofile'),
        ),
    ]
